import type { EventCategory } from '@/src/types/events';

export const AUTH = {
  LOGIN_TITLE: 'Iniciar Sesión',
  LOGIN_SUBTITLE: 'Accede a tu cuenta de Event Booking',
  LOGIN_EMAIL_LABEL: 'Correo electrónico',
  LOGIN_EMAIL_PLACEHOLDER: 'Ingresa tu correo',
  LOGIN_PASSWORD_LABEL: 'Contraseña',
  LOGIN_PASSWORD_PLACEHOLDER: 'Ingresa tu contraseña',
  LOGIN_BUTTON: 'Ingresar',
  LOGIN_NO_ACCOUNT: '¿No tienes cuenta?',
  LOGIN_REGISTER_LINK: 'Regístrate',
  REGISTER_TITLE: 'Crear Cuenta',
  REGISTER_SUBTITLE: 'Regístrate para reservar eventos',
  REGISTER_FIRST_NAME_LABEL: 'Nombre',
  REGISTER_FIRST_NAME_PLACEHOLDER: 'Ingresa tu nombre',
  REGISTER_LAST_NAME_LABEL: 'Apellido',
  REGISTER_LAST_NAME_PLACEHOLDER: 'Ingresa tu apellido',
  REGISTER_EMAIL_LABEL: 'Correo electrónico',
  REGISTER_EMAIL_PLACEHOLDER: 'Ingresa tu correo',
  REGISTER_PHONE_LABEL: 'Teléfono (opcional)',
  REGISTER_PHONE_PLACEHOLDER: 'Ingresa tu teléfono',
  REGISTER_PASSWORD_LABEL: 'Contraseña',
  REGISTER_PASSWORD_PLACEHOLDER: 'Crea una contraseña',
  REGISTER_CONFIRM_PASSWORD_LABEL: 'Confirmar contraseña',
  REGISTER_CONFIRM_PASSWORD_PLACEHOLDER: 'Confirma tu contraseña',
  REGISTER_BUTTON: 'Registrarse',
  REGISTER_HAS_ACCOUNT: '¿Ya tienes cuenta?',
  REGISTER_LOGIN_LINK: 'Inicia sesión',
  LOGOUT_LABEL: 'Cerrar sesión',
  SESSION_RESTORE: 'Restaurando sesión...',
  REGISTERED_SUCCESS: 'Cuenta creada exitosamente. Ahora puedes iniciar sesión.',
  LOGOUT_SUCCESS: 'Sesión cerrada correctamente.',
} as const;

export const CATEGORY: {
  COLORS: Record<EventCategory, string>;
  LABELS: Record<EventCategory, string>;
} = {
  COLORS: {
    sports: '#2196F3',
    music: '#9C27B0',
    culture: '#FF9800',
    gastronomy: '#F44336',
    wellness: '#4CAF50',
    education: '#00BCD4',
    other: '#607D8B',
  },
  LABELS: {
    sports: 'Deportes',
    music: 'Música',
    culture: 'Cultura',
    gastronomy: 'Gastronomía',
    wellness: 'Bienestar',
    education: 'Educación',
    other: 'Otro',
  },
};

export const EVENTS = {
  CREATE_TITLE: 'Crear Evento',
  CREATE_SUBTITLE: 'Ingresa los detalles del nuevo evento',
  CREATE_TITLE_LABEL: 'Título',
  CREATE_TITLE_PLACEHOLDER: 'Nombre del evento',
  CREATE_DESCRIPTION_LABEL: 'Descripción',
  CREATE_DESCRIPTION_PLACEHOLDER: 'Breve descripción del evento',
  CREATE_CAPACITY_LABEL: 'Capacidad máxima',
  CREATE_CAPACITY_PLACEHOLDER: 'Ej. 100',
  CREATE_CATEGORY_LABEL: 'Categoría',
  CREATE_CATEGORY_PLACEHOLDER: 'Selecciona una categoría',
  CREATE_DATE_LABEL: 'Fecha',
  CREATE_DATE_PLACEHOLDER: 'Selecciona una fecha',
  CREATE_START_LABEL: 'Hora de Inicio',
  CREATE_START_PLACEHOLDER: 'Selecciona hora de inicio',
  CREATE_END_LABEL: 'Hora de Fin',
  CREATE_END_PLACEHOLDER: 'Selecciona hora de fin',
  CREATE_IMAGE_LABEL: 'Imagen (opcional, máx 5 MB)',
  CREATE_IMAGE_SELECT: 'Seleccionar Imagen',
  CREATE_IMAGE_CHANGE: 'Cambiar Imagen',
  CREATE_CATEGORY_ACCESSIBILITY: 'Seleccionar categoría',
  CREATE_DATE_ACCESSIBILITY: 'Seleccionar fecha',
  CREATE_START_ACCESSIBILITY: 'Seleccionar hora de inicio',
  CREATE_END_ACCESSIBILITY: 'Seleccionar hora de fin',
  CREATE_IMAGE_SELECT_ACCESSIBILITY: 'Seleccionar imagen del evento',
  CREATE_IMAGE_CHANGE_ACCESSIBILITY: 'Cambiar imagen del evento',
  CREATE_IMAGE_PREVIEW_ACCESSIBILITY: 'Vista previa de la imagen del evento',
  CREATE_BUTTON: 'Crear Evento',
  CREATE_MODAL_DATE_TITLE: 'Fecha del evento',
  CREATE_MODAL_START_TITLE: 'Hora de inicio',
  CREATE_MODAL_END_TITLE: 'Hora de fin',
  CREATE_MODAL_CATEGORY_TITLE: 'Categoría',
  CREATE_MODAL_DONE: 'Listo',
  FEED_LOADING: 'Cargando eventos...',
  FEED_EMPTY_TITLE: 'Sin eventos',
  FEED_EMPTY_SUBTITLE: 'No hay eventos disponibles en este momento',
  FEED_ERROR_RETRY: 'Reintentar',
  EVENT_CREATED: 'Evento creado exitosamente.',
  EDIT_TITLE: 'Editar Evento',
  EDIT_SUBTITLE: 'Modifica los detalles del evento',
  EDIT_BUTTON: 'Guardar Cambios',
  EDIT_LOADING: 'Cargando evento...',
  EDIT_CONFIRM_TITLE: '¿Confirmar cambios?',
  EDIT_CONFIRM_MESSAGE: 'Esta acción es irreversible. Los cambios se reflejarán inmediatamente para todos los usuarios. ¿Deseas continuar?',
  EDIT_CONFIRM_CANCEL: 'Cancelar',
  EDIT_CONFIRM_OK: 'Sí, guardar cambios',
  EDIT_SUCCESS: 'Evento actualizado exitosamente.',
  DETAIL_LOADING: 'Cargando evento...',
  DETAIL_NOT_FOUND: 'Evento no encontrado',
  DETAIL_DATE_LABEL: 'Fecha',
  DETAIL_START_LABEL: 'Hora de inicio',
  DETAIL_END_LABEL: 'Hora de fin',
  DETAIL_CAPACITY_LABEL: 'Cupos disponibles',
  DETAIL_BOOK_BUTTON: 'Reservar',
  LOGIN_MODAL_TITLE: 'Inicia sesión para continuar',
  LOGIN_MODAL_BODY: 'Necesitas una cuenta para reservar este evento.',
  LOGIN_MODAL_BUTTON: 'Iniciar sesión',
  LOGIN_MODAL_CANCEL: 'Cancelar',
  CAPACITY_FULL: 'Lleno',
  CAPACITY_SLOT: 'cupo',
  CAPACITY_SLOTS: 'cupos',
} as const;

export const VALIDATION = {
  TITLE_REQUIRED: 'El título es obligatorio',
  TITLE_MIN: 'El título debe tener al menos 3 caracteres',
  TITLE_MAX: 'El título no puede exceder 64 caracteres',
  DESCRIPTION_MAX: 'La descripción no puede exceder 255 caracteres',
  CAPACITY_REQUIRED: 'La capacidad máxima es obligatoria',
  CAPACITY_INVALID: 'La capacidad debe ser al menos 1',
  CAPACITY_MAX: 'La capacidad no puede exceder 9999999',
  CATEGORY_REQUIRED: 'La categoría es obligatoria',
  CATEGORY_INVALID: 'La categoría seleccionada no es válida',
  DATE_REQUIRED: 'La fecha es obligatoria',
  DATE_PAST: 'La fecha no puede ser en el pasado',
  START_TIME_PAST: 'La hora de inicio no puede estar en el pasado',
  START_REQUIRED: 'La hora de inicio es obligatoria',
  END_REQUIRED: 'La hora de fin es obligatoria',
  END_BEFORE_START: 'La hora de fin debe ser posterior a la de inicio',
  EMAIL_REQUIRED: 'El correo electrónico es obligatorio',
  EMAIL_INVALID: 'Ingresa un correo electrónico válido',
  EMAIL_MAX: 'El correo no puede exceder 150 caracteres',
  PASSWORD_REQUIRED: 'La contraseña es obligatoria',
  PASSWORD_MAX: 'La contraseña no puede exceder 255 caracteres',
  FIRST_NAME_REQUIRED: 'El nombre es obligatorio',
  FIRST_NAME_MIN: 'El nombre debe tener al menos 2 caracteres',
  FIRST_NAME_MAX: 'El nombre no puede exceder 50 caracteres',
  FIRST_NAME_LETTERS: 'El nombre solo puede contener letras',
  LAST_NAME_REQUIRED: 'El apellido es obligatorio',
  LAST_NAME_MIN: 'El apellido debe tener al menos 2 caracteres',
  LAST_NAME_MAX: 'El apellido no puede exceder 50 caracteres',
  LAST_NAME_LETTERS: 'El apellido solo puede contener letras',
  PASSWORD_MIN: 'La contraseña debe tener al menos 8 caracteres',
  PASSWORD_UPPER: 'La contraseña debe contener al menos una mayúscula',
  PASSWORD_LOWER: 'La contraseña debe contener al menos una minúscula',
  PASSWORD_NUMBER: 'La contraseña debe contener al menos un número',
  PASSWORD_SPECIAL: 'La contraseña debe contener al menos un carácter especial',
  CONFIRM_REQUIRED: 'Confirma tu contraseña',
  CONFIRM_MISMATCH: 'Las contraseñas no coinciden',
  PHONE_DIGITS: 'El teléfono debe tener exactamente 8 dígitos',
  IMAGE_FORMAT: 'La imagen debe estar en formato PNG, JPG o WebP.',
} as const;

export const ERRORS = {
  NETWORK: 'No se pudo conectar con el servidor. Verifica tu conexión a internet.',
  GENERIC: 'Ocurrió un error inesperado. Intenta nuevamente.',
  INVALID_CREDENTIALS: 'Credenciales inválidas. Verifica tu correo y contraseña.',
  VALIDATION_BANNER: 'Revisa los campos ingresados e intenta nuevamente.',
  SCHEDULE_CONFLICT: 'Ya existe un evento programado en esta fecha y horario. Por favor selecciona otro.',
  EVENTS_LOAD_ERROR: 'Error al cargar los eventos',
  EVENT_LOAD_ERROR: 'Error al cargar el evento',
  EVENT_UPDATE_ERROR: 'Error al actualizar el evento',
  CALENDAR_LOAD_ERROR: 'No se pudo cargar el calendario.',
  CALENDAR_EVENTS_ERROR: 'No se pudieron cargar los eventos del día.',
} as const;

export const ADMIN = {
  CALENDAR_TITLE: 'Calendario',
  CALENDAR_SUBTITLE: 'Consulta la disponibilidad de eventos',
  CREATE_EVENT_NAV: 'Prueba temporal: Crear Evento',
  EDIT_EVENT_NAV: 'Prueba temporal: Editar Evento',
  EDIT_EVENT_PLACEHOLDER: 'Selecciona un evento',
  EDIT_EVENT_ACCESSIBILITY: 'Seleccionar evento para editar',
  EDIT_EVENT_MODAL_TITLE: 'Eventos disponibles',
  EDIT_EVENT_LOADING: 'Cargando eventos...',
  CALENDAR_EMPTY_TITLE: 'Selecciona un día',
  CALENDAR_EMPTY_SUBTITLE: 'Toca un día en el calendario para ver sus eventos',
  CALENDAR_NO_EVENTS_TITLE: 'Sin eventos',
  CALENDAR_NO_EVENTS_SUBTITLE: 'No hay eventos programados para este día',
  CALENDAR_LOADING_EVENTS: 'Cargando eventos...',
  CALENDAR_LOADING: 'Cargando...',
  CALENDAR_EVENTS_FOR_DAY: 'Eventos del',
  CALENDAR_EVENTS_TITLE: 'Eventos del día',
  CREATE_EVENT_FAB_LABEL: 'Crear evento',
  HEADER_TITLE: 'Event Booking',
} as const;

export const CUSTOMER = {
  EVENTS_TAB: 'Eventos',
  RESERVATIONS_TAB: 'Reservas',
  EVENTS_TITLE: 'Eventos',
  EVENTS_SUBTITLE: 'Explora los eventos disponibles',
  RESERVATIONS_TITLE: 'Mis Reservas',
  RESERVATIONS_SUBTITLE: 'Historial y estado de tus reservaciones',
} as const;

export const RESERVATIONS = {
  LIST_TITLE: 'Reservaciones',
  LIST_SUBTITLE: 'Gestión de reservas del evento',
  LIST_LOADING: 'Cargando reservaciones...',
  LIST_EMPTY_TITLE: 'Sin reservaciones',
  LIST_EMPTY_SUBTITLE: 'No hay reservaciones activas para este evento',
  LIST_ERROR: 'Error al cargar las reservaciones',
  SEARCH_PLACEHOLDER: 'Buscar por nombre o correo...',
  CANCEL_BUTTON: 'Cancelar',
  CANCEL_CONFIRM_TITLE: '¿Cancelar reservación?',
  CANCEL_CONFIRM_MESSAGE: 'Esta acción es irreversible. Los cupos se liberarán automáticamente.',
  CANCEL_CONFIRM_OK: 'Sí, cancelar',
  CANCEL_CONFIRM_CANCEL: 'No',
  CANCEL_LOADING: 'Cancelando...',
  CANCEL_SUCCESS: 'Reservación cancelada exitosamente.',
  CANCEL_ERROR: 'Error al cancelar la reservación',
  VIEW_RESERVATIONS: 'Ver reservaciones',
  SLOTS_LABEL: 'cupos',
  SLOT_LABEL: 'cupo',
} as const;
